// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJd1r_7YnwYOClc5ur1xyg8ZfWRCNLipQ',
    appId: '1:1068664914210:web:b5086d2525e2ef85b2257b',
    messagingSenderId: '1068664914210',
    projectId: 'multivendorapplication-c74a0',
    authDomain: 'multivendorapplication-c74a0.firebaseapp.com',
    storageBucket: 'multivendorapplication-c74a0.appspot.com',
    measurementId: 'G-L1531JTDXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBzGEBkOhvQBFulODV40C7jOCFK7csHPg',
    appId: '1:1068664914210:android:2eb8eacddd2b6a78b2257b',
    messagingSenderId: '1068664914210',
    projectId: 'multivendorapplication-c74a0',
    storageBucket: 'multivendorapplication-c74a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgq_qS6DT7ZZckW1pGwx060Uwuz-qF1eE',
    appId: '1:1068664914210:ios:214789097e2e7ef0b2257b',
    messagingSenderId: '1068664914210',
    projectId: 'multivendorapplication-c74a0',
    storageBucket: 'multivendorapplication-c74a0.appspot.com',
    androidClientId: '1068664914210-aqmacoapdalo2sn8d5n344uj9cb131nt.apps.googleusercontent.com',
    iosClientId: '1068664914210-kdv6n4rb3su0mg2t0g0buvagnt8e8rhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.cncAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgq_qS6DT7ZZckW1pGwx060Uwuz-qF1eE',
    appId: '1:1068664914210:ios:65cd541b28987497b2257b',
    messagingSenderId: '1068664914210',
    projectId: 'multivendorapplication-c74a0',
    storageBucket: 'multivendorapplication-c74a0.appspot.com',
    androidClientId: '1068664914210-aqmacoapdalo2sn8d5n344uj9cb131nt.apps.googleusercontent.com',
    iosClientId: '1068664914210-8de1ul706fkbd67mc1hfngrv4ua6ar73.apps.googleusercontent.com',
    iosBundleId: 'com.example.cncAdmin.RunnerTests',
  );
}
